Shop/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('auth/', include('main.auth.urls')),
    path('', include('main.dashboard.urls')),
]+static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

main/dashboard/urls.py
from django.urls import path
from . import views

app_name = 'dashboard'

urlpatterns = [
    path('', views.index, name='index'),
    # --- CATEGORY ---
    path('category-list/', views.category_list, name='category_list'),
    path('category-create/', views.category_create, name='category_create'),
    path('category-delete/<str:code>/', views.category_delete, name='category_delete'),
    # --- PRODUCT ---
    path('product-list/', views.product_list, name='product_list'),
    path('product-create/', views.product_create, name='product_create'),
    path('product-detail/<str:code>/', views.product_detail, name='product_detail'),
    path('product-delete/<str:code>/', views.product_delete, name='product_delete'),
    # --- ENTER ---
    path('enter-list/', views.enter_list, name='enter_list'),
    path('enter-create/', views.enter_create, name='enter_create'),
    path('enter-delete/<str:code>/', views.enter_delete, name='enter_delete'),
    # --- OUT ---
    path('out-list/', views.out_list, name='out_list'),
    path('out-create/', views.out_create, name='out_create'),
    path('out-delete/<str:code>/', views.out_delete, name='out_delete'),
    path('order-return/<str:code>/', views.order_return, name='order_return'),
    # --- ORDER ---
    path('order-list/', views.order_list, name='order_list'),
    path('order-create/', views.order_create, name='order_create'),
    path('order-delete/<str:code>/', views.order_delete, name='order_delete'),
    # --- ORDER PRODUCT ---
    path('order-product-list/', views.order_product_list, name='order_product_list'),
    path('order-product-list/<str:code>/', views.order_product_list, name='order_product_list'),
    path('order-product-create/', views.order_product_create, name='order_product_create'),
    path('order-product-delete/<str:code>/', views.order_product_delete, name='order_product_delete'),
]

main/dashboard/views.py
from django.shortcuts import render, redirect
from .. import models
from datetime import datetime
from itertools import chain


def staff_required(func):
    def wrapper(request, *args, **kwargs):
        if request.user.is_authenticated and request.user.is_staff:
            result = func(request, *args, **kwargs)
        else:
            return redirect('auth:login')
        return result
    return wrapper



@staff_required 
def index(request):
    products = models.Product.objects.all()
    enters = models.Enter.objects.all()
    outs = models.Out.objects.all()
    total_enter = sum(enter.total for enter in enters)
    total_out = sum(out.total for out in outs)
    all = list(chain(enters, outs))
    #
    # if request.method == 'GET':
    #     product_code = request.GET.get('product_code')
    #     filter_items = {}
    #     for key, value in request.GET.items():
    #         if key == 'product_code' and value == '0':
    #             continue
    #         if value:
    #             if key == 'product_code':
    #                 key = 'product__code'
    #                 filter_items[key] = False
    #                 continue
    #             filter_items[key] = value
    #     def filter_func(item):
    #         for key, value in filter_items.items():
    #             if key == 'product__code' and item.product.code != value:
    #                 return False
    #         return True
    
    # all = list(filter(filter_func, all))
    #
    context = {'product_count':products.count(), 'all':all, 'queryset':products, 'total_enter':total_enter, 'total_out':total_out}
    return render(request, 'dashboard/index.html', context)

# ---------- CATEGORY ----------

@staff_required 
def category_list(request):
    queryset = models.Category.objects.all()
    return render(request, 'dashboard/category/list.html', {'queryset':queryset})

@staff_required 
def category_create(request):
    if request.method == 'POST':
        models.Category.objects.create(
            name = request.POST['name']
        )
        return redirect('dashboard:category_list')
    return render(request, 'dashboard/category/create.html')

@staff_required 
def category_delete(request, code):
    queryset = models.Category.objects.get(code=code)
    queryset.delete()
    return redirect('dashboard:category_list')

# ---------- PRODUCT ----------

@staff_required
def product_list(request):
    queryset = models.Product.objects.all()
    return render(request, 'dashboard/product/list.html', {'queryset':queryset})

@staff_required
def product_create(request):
    categories = models.Category.objects.all()
    if request.method == 'POST':
        discount_price = request.POST.get('discount_price')
        models.Product.objects.create(
            name = request.POST.get('name'),
            category = models.Category.objects.get(code=request.POST.get('category_code')),
            price = float(request.POST.get('price')),
            discount_price = float(discount_price) if discount_price else None,
            quantity = 0,
            banner_image = request.FILES.get('banner_image'),
        )
        return redirect('dashboard:product_list')
    return render(request, 'dashboard/product/create.html', {'categories':categories})

@staff_required
def product_detail(request, code):
    queryset = models.Product.objects.get(code=code)
    images = models.ProductImage.objects.filter(product=queryset)
    videos = models.ProductVideo.objects.filter(product=queryset)
    context = {
        'product':queryset,
        'images':images,
        'videos':videos,
    }
    return render(request, 'dashboard/product/detail.html', context)

@staff_required
def product_delete(request, code):
    models.Product.objects.get(code=code).delete()
    return redirect('dashboard:product_list')
    

# ---------- ENTER ----------

@staff_required
def enter_list(request):
    queryset = models.Enter.objects.all()
    return render(request, 'dashboard/enter/list.html', {'queryset':queryset})

@staff_required
def enter_create(request):
    queryset = models.Product.objects.all()
    if request.method == 'POST':
        product = models.Product.objects.get(code=request.POST['code'])
        quantity = request.POST['quantity']
        models.Enter.objects.create(
            product=product,
            quantity=int(quantity),
            date = datetime.now()
        )
        return redirect('dashboard:enter_list')
    return render(request, 'dashboard/enter/create.html', {'queryset':queryset})

@staff_required
def enter_delete(request, code):
    models.Enter.objects.get(code=code).delete()
    return redirect('dashboard:enter_list')

# ---------- OUT ----------

@staff_required
def out_list(request):
    queryset = models.Out.objects.all()
    return render(request, 'dashboard/out/list.html', {'queryset':queryset})

@staff_required
def out_create(request):
    queryset = models.Product.objects.all()
    if request.method == 'POST':
        product = models.Product.objects.get(code=request.POST['code'])
        quantity = request.POST['quantity']
        models.Out.objects.create(
            product=product,
            quantity=int(quantity),
        )
        return redirect('dashboard:out_list')
    return render(request, 'dashboard/out/create.html', {'queryset':queryset})

@staff_required
def out_delete(request, code):
    models.Out.objects.get(code=code).delete()
    return redirect('dashboard:out_list')

# ---------- ORDER ----------

@staff_required
def order_list(request):
    queryset = models.Order.objects.all()
    return render(request, 'dashboard/order/list.html', {'queryset':queryset})

@staff_required
def order_create(request):
    if request.method == 'POST':
        models.Order.objects.create(
            name=request.POST['name'],
            is_returned=False,
        )
        return redirect('dashboard:order_list')
    return render(request, 'dashboard/order/create.html')

@staff_required
def order_delete(request, code):
    models.Order.objects.get(code=code).delete()
    return redirect('dashboard:order_list')

def order_return(request, code):
    order = models.Order.objects.get(code=code)
    order.is_returned = True
    order.save
    return redirect('dashboard:order_list')

# ---------- ORDER PRODUCT ----------

@staff_required
def order_product_list(request, code):
    if code:
        queryset = models.OrderProduct.objects.filter(order__code = code)
    else:
        queryset = models.OrderProduct.objects.all()
    return render(request, 'dashboard/order_product/list.html', {'queryset':queryset})

@staff_required
def order_product_create(request):
    products = models.Product.objects.all()
    orders = models.Order.objects.all()
    if request.method == 'POST':
        models.OrderProduct.objects.create(
            product = models.Product.objects.get(code=request.POST.get('product_code')),
            order = models.Order.objects.get(code=request.POST.get('order_code')),
            quantity = request.POST.get('quantity')
        )
        models.Out.objects.create(
            product = models.Product.objects.get(code=request.POST.get('product_code')),
            quantity = request.POST.get('quantity'),
        )
        return redirect('dashboard:order_list')
    return render(request, 'dashboard/order_product/create.html', {'products':products, 'orders':orders})

@staff_required
def order_product_delete(request, code):
    models.OrderProduct.objects.get(code=code).delete()
    return redirect('dashboard:order_product_list')

templates/dashboard/product/create.html
{% extends 'dashboard/base.html' %}
{% load static %}
{% block content %}
<form class="forms-sample" method="post" enctype="multipart/form-data">
    {% csrf_token %}
    <div class="form-group">
        <label for="exampleInputName1">Nomi</label>
        <input name="name" type="text" class="form-control" id="exampleInputName1" placeholder="Nomni kiriting">
    </div>
    <div class="form-group">
        <label for="exampleFormControlSelect2">Kategoriya</label>
        <select name="category_code" class="form-select" id="exampleFormControlSelect2">
            {% for category in categories %}
            <option value="{{category.code}}">{{category.name}}</option>
            {% endfor %}
        </select>
    </div>
    <div class="form-group">
        <div class="input-group">
          <div class="input-group-prepend">
            <span class="input-group-text bg-gradient-primary text-white">Narxi </span>
          </div>
          <input name="price" type="text" class="form-control" aria-label="Amount (to the nearest dollar)">
          <div class="input-group-append">
            <span class="input-group-text">.00</span>
          </div>
        </div>
    </div>
    <div class="form-group">
        <div class="input-group">
          <div class="input-group-prepend">
            <span class="input-group-text bg-gradient-primary text-white">Chegirma narxi </span>
          </div>
          <input name="discount_price" type="text" class="form-control" aria-label="Amount (to the nearest dollar)">
          <div class="input-group-append">
            <span class="input-group-text">.00</span>
          </div>
        </div>
    </div>
    <div class="mb-3">
      <label for="formFile" class="form-label">Upload Banner Image</label>
      <input name="banner_image" class="form-control" type="file" id="formFile" accept="image/*">
    </div>
    <button type="submit" class="btn btn-success">Yaratish</button>
</form>
{% endblock content %}

templates/dashboard/product/detail.html
{% extends 'dashboard/base.html' %}
{% load static %}
{% block content %}
<div class="card">
    <div class="card-body" style="display: block;">
        <h4 class="card-title">Nomi</h4>
        <h3>{{product.name}}</h3>
    </div>
    <div class="card-body" style="display: block;">
        <h4 class="card-title">Kategoriya</h4>
        <h3>{{product.category}}</h3>
    </div>
    <div class="card-body">
        <h4 class="card-title">Narxi</h4>
        <h3>{{product.price}}</h3>
    </div>
{% if product.discount_price %}
    <div class="card-body">
        <h4 class="card-title">Chegirma narxi</h4>
        <h3>{{product.discount_price}}</h3>
    </div>
{% endif %}
    <div class="card-body">
        <h4 class="card-title">Miqdori</h4>
        <h3>{{product.quantity}}</h3>
    </div>
    <div class="card-body">
        <h4 class="card-title">Rasmi</h4>
        <img src="{{product.banner_image.url}}" style="width: 20rem; height: 20rem;"  alt="">
    </div>
    <div class="card-body">
        <h4 class="card-title">QR kod</h4>
        <img src="{{product.qrcode_img.url}}" alt="">
    </div>
</div>
{% endblock content %}

templates/dashboard/product/list.html
{% extends 'dashboard/base.html' %}
{% load static %}
{% block content %}
<div class="col-lg-6 grid-margin stretch-card">
    <div class="card">
      <div class="card-body">
        <h4 class="card-title">Mahsulotlar</h4>
        </p>
        <table class="table">
          <thead>
            <tr>
              <th>Nomi</th>
              <th>Kategoriyasi</th>
              <th>Narxi</th>
              <th>Chegirma narxi</th>
              <th>Soni</th>
              <th>Rasm</th>
              <th>Harakatlar</th>
            </tr>
          </thead>
          <tbody>
            {% for product in queryset %}
            <tr>
              <td>{{product.name}}</td>
              <td>{{product.category}}</td>
              <td>{{product.price}}</td>
              {% if product.discount_price %}
              <td>{{product.discount_price}}</td>
              {% else %}
              <td><button class="btn btn-danger" disabled></button></td>
              {% endif %}
              <td>{{product.quantity}}</td>
              <td><img src="{{product.banner_image.url}}" style="width: 4rem; height: 4rem;"></td>
              <td>
                <a href="{% url 'dashboard:product_delete' product.code %}"><button class="btn btn-danger">O'chirish</button></a>
                <a href="{% url 'dashboard:product_detail' product.code %}"><button class="btn btn-info">Ma'lumot</button></a>
              </td> 
            </tr>
            {% endfor %}
          </tbody>
        </table>
      </div>
    </div>
  </div>
{% endblock content %}