Shop/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('auth/', include('main.auth.urls')),
    path('', include('main.dashboard.urls')),
]+static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

main/auth/urls.py
from django.urls import path
from . import views

app_name = 'auth'

urlpatterns = [
    path('register/', views.register, name='register'),
    path('login/', views.log_in, name='login'),
    path('logout/', views.log_out, name='logout'),
]

main/dashboard/urls.py
from django.urls import path
from . import views

app_name = 'dashboard'

urlpatterns = [
    path('', views.index, name='index'),
    # --- CATEGORY ---
    path('category-list/', views.category_list, name='category_list'),
    path('category-create/', views.category_create, name='category_create'),
    path('category-delete/<str:code>/', views.category_delete, name='category_delete'),
    # --- PRODUCT ---
    path('product-list/', views.product_list, name='product_list'),
    path('product-create/', views.product_create, name='product_create'),
    path('product-detail/<str:code>/', views.product_detail, name='product_detail'),
    path('product-delete/<str:code>/', views.product_delete, name='product_delete'),
    # --- ENTER ---
    path('enter-list/', views.enter_list, name='enter_list'),
    path('enter-create/', views.enter_create, name='enter_create'),
    path('enter-delete/<str:code>/', views.enter_delete, name='enter_delete'),
    # --- OUT ---
    path('out-list/', views.out_list, name='out_list'),
    path('out-create/', views.out_create, name='out_create'),
    path('out-delete/<str:code>/', views.out_delete, name='out_delete'),
    path('order-return/<str:code>/', views.order_return, name='order_return'),
    # --- ORDER ---
    path('order-list/', views.order_list, name='order_list'),
    path('order-create/', views.order_create, name='order_create'),
    path('order-delete/<str:code>/', views.order_delete, name='order_delete'),
    # --- ORDER PRODUCT ---
    path('order-product-list/', views.order_product_list, name='order_product_list'),
    path('order-product-list/<str:code>/', views.order_product_list, name='order_product_list'),
    path('order-product-create/', views.order_product_create, name='order_product_create'),
    path('order-product-delete/<str:code>/', views.order_product_delete, name='order_product_delete'),
]

main/dashboard/views.py
from django.shortcuts import render, redirect
from .. import models
from datetime import datetime
from itertools import chain


def staff_required(func):
    def wrapper(request, *args, **kwargs):
        if request.user.is_authenticated and request.user.is_staff:
            result = func(request, *args, **kwargs)
        else:
            return redirect('auth:login')
        return result
    return wrapper



@staff_required 
def index(request):
    products = models.Product.objects.all()
    enters = models.Enter.objects.all()
    outs = models.Out.objects.all()
    total_enter = sum(enter.total for enter in enters)
    total_out = sum(out.total for out in outs)
    all = list(chain(enters, outs))
    #
    # if request.method == 'GET':
    #     product_code = request.GET.get('product_code')
    #     filter_items = {}
    #     for key, value in request.GET.items():
    #         if key == 'product_code' and value == '0':
    #             continue
    #         if value:
    #             if key == 'product_code':
    #                 key = 'product__code'
    #                 filter_items[key] = False
    #                 continue
    #             filter_items[key] = value
    #     def filter_func(item):
    #         for key, value in filter_items.items():
    #             if key == 'product__code' and item.product.code != value:
    #                 return False
    #         return True
    
    # all = list(filter(filter_func, all))
    #
    context = {'product_count':products.count(), 'all':all, 'queryset':products, 'total_enter':total_enter, 'total_out':total_out}
    return render(request, 'dashboard/index.html', context)

# ---------- CATEGORY ----------

@staff_required 
def category_list(request):
    queryset = models.Category.objects.all()
    return render(request, 'dashboard/category/list.html', {'queryset':queryset})

@staff_required 
def category_create(request):
    if request.method == 'POST':
        models.Category.objects.create(
            name = request.POST['name']
        )
        return redirect('dashboard:category_list')
    return render(request, 'dashboard/category/create.html')

@staff_required 
def category_delete(request, code):
    queryset = models.Category.objects.get(code=code)
    queryset.delete()
    return redirect('dashboard:category_list')

# ---------- PRODUCT ----------

@staff_required
def product_list(request):
    queryset = models.Product.objects.all()
    return render(request, 'dashboard/product/list.html', {'queryset':queryset})

@staff_required
def product_create(request):
    categories = models.Category.objects.all()
    if request.method == 'POST':
        discount_price = request.POST.get('discount_price')
        models.Product.objects.create(
            name = request.POST.get('name'),
            category = models.Category.objects.get(code=request.POST.get('category_code')),
            price = float(request.POST.get('price')),
            discount_price = float(discount_price) if discount_price else None,
            quantity = 0,
            banner_image = request.FILES.get('banner_image'),
        )
        return redirect('dashboard:product_list')
    return render(request, 'dashboard/product/create.html', {'categories':categories})

@staff_required
def product_detail(request, code):
    queryset = models.Product.objects.get(code=code)
    images = models.ProductImage.objects.filter(product=queryset)
    videos = models.ProductVideo.objects.filter(product=queryset)
    context = {
        'product':queryset,
        'images':images,
        'videos':videos,
    }
    return render(request, 'dashboard/product/detail.html', context)

@staff_required
def product_delete(request, code):
    models.Product.objects.get(code=code).delete()
    return redirect('dashboard:product_list')
    

# ---------- ENTER ----------

@staff_required
def enter_list(request):
    queryset = models.Enter.objects.all()
    return render(request, 'dashboard/enter/list.html', {'queryset':queryset})

@staff_required
def enter_create(request):
    queryset = models.Product.objects.all()
    if request.method == 'POST':
        product = models.Product.objects.get(code=request.POST['code'])
        quantity = request.POST['quantity']
        models.Enter.objects.create(
            product=product,
            quantity=int(quantity),
            date = datetime.now()
        )
        return redirect('dashboard:enter_list')
    return render(request, 'dashboard/enter/create.html', {'queryset':queryset})

@staff_required
def enter_delete(request, code):
    models.Enter.objects.get(code=code).delete()
    return redirect('dashboard:enter_list')

# ---------- OUT ----------

@staff_required
def out_list(request):
    queryset = models.Out.objects.all()
    return render(request, 'dashboard/out/list.html', {'queryset':queryset})

@staff_required
def out_create(request):
    queryset = models.Product.objects.all()
    if request.method == 'POST':
        product = models.Product.objects.get(code=request.POST['code'])
        quantity = request.POST['quantity']
        models.Out.objects.create(
            product=product,
            quantity=int(quantity),
        )
        return redirect('dashboard:out_list')
    return render(request, 'dashboard/out/create.html', {'queryset':queryset})

@staff_required
def out_delete(request, code):
    models.Out.objects.get(code=code).delete()
    return redirect('dashboard:out_list')

# ---------- ORDER ----------

@staff_required
def order_list(request):
    queryset = models.Order.objects.all()
    return render(request, 'dashboard/order/list.html', {'queryset':queryset})

@staff_required
def order_create(request):
    if request.method == 'POST':
        models.Order.objects.create(
            name=request.POST['name'],
            is_returned=False,
        )
        return redirect('dashboard:order_list')
    return render(request, 'dashboard/order/create.html')

@staff_required
def order_delete(request, code):
    models.Order.objects.get(code=code).delete()
    return redirect('dashboard:order_list')

def order_return(request, code):
    order = models.Order.objects.get(code=code)
    order.is_returned = True
    order.save
    return redirect('dashboard:order_list')

# ---------- ORDER PRODUCT ----------

@staff_required
def order_product_list(request, code):
    if code:
        queryset = models.OrderProduct.objects.filter(order__code = code)
    else:
        queryset = models.OrderProduct.objects.all()
    return render(request, 'dashboard/order_product/list.html', {'queryset':queryset})

@staff_required
def order_product_create(request):
    products = models.Product.objects.all()
    orders = models.Order.objects.all()
    if request.method == 'POST':
        models.OrderProduct.objects.create(
            product = models.Product.objects.get(code=request.POST.get('product_code')),
            order = models.Order.objects.get(code=request.POST.get('order_code')),
            quantity = request.POST.get('quantity')
        )
        models.Out.objects.create(
            product = models.Product.objects.get(code=request.POST.get('product_code')),
            quantity = request.POST.get('quantity'),
        )
        return redirect('dashboard:order_list')
    return render(request, 'dashboard/order_product/create.html', {'products':products, 'orders':orders})

@staff_required
def order_product_delete(request, code):
    models.OrderProduct.objects.get(code=code).delete()
    return redirect('dashboard:order_product_list')

templates/dashboard/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
  <head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <title>Purple Admin</title>
    <!-- plugins:css -->
    <link rel="stylesheet" href="{% static 'vendors/mdi/css/materialdesignicons.min.css' %}">
    <link rel="stylesheet" href="{% static 'vendors/ti-icons/css/themify-icons.css' %}">
    <link rel="stylesheet" href="{% static 'vendors/css/vendor.bundle.base.css' %}">
    <link rel="stylesheet" href="{% static 'vendors/font-awesome/css/font-awesome.min.css' %}">
    <!-- endinject -->
    <!-- Plugin css for this page -->
    <link rel="stylesheet" href="{% static 'vendors/font-awesome/css/font-awesome.min.css' %}" />
    <link rel="stylesheet" href="{% static 'vendors/bootstrap-datepicker/bootstrap-datepicker.min.css' %}">
    <!-- End plugin css for this page -->
    <!-- inject:css -->
    <!-- endinject -->
    <!-- Layout styles -->
    <link rel="stylesheet" href="{% static 'css/style.css' %}">
    <!-- End layout styles -->
    <link rel="shortcut icon" href="{% static 'images/favicon.png' %}" />
  </head>
  <body>
      <!-- partial:partials/_navbar.html -->
      <nav class="navbar default-layout-navbar col-lg-12 col-12 p-0 fixed-top d-flex flex-row">
        <div class="text-center navbar-brand-wrapper d-flex align-items-center justify-content-start">
        </div>
        <div class="navbar-menu-wrapper d-flex align-items-stretch">
          <button class="navbar-toggler navbar-toggler align-self-center" type="button" data-toggle="minimize">
            <span class="mdi mdi-menu"></span>
          </button>
          <div class="search-field d-none d-md-block">
            <form class="d-flex align-items-center h-100" action="#">
              <div class="input-group">
                <div class="input-group-prepend bg-transparent">
                </div>
              </div>
            </form>
          </div>
          <ul class="navbar-nav navbar-nav-right">
            <li class="nav-item nav-profile dropdown">
              <a class="nav-link dropdown-toggle" id="profileDropdown" href="#" data-bs-toggle="dropdown" aria-expanded="false">
                <div class="nav-profile-img">
                  <img src="{% static 'images/faces/images.png' %}" alt="image">
                  <span class="availability-status online"></span>
                </div>
                <div class="nav-profile-text">
                  <p class="mb-1 text-black">{{user.username}}</p>
                </div>
              </a>
              <div class="dropdown-menu navbar-dropdown" aria-labelledby="profileDropdown">
                <div class="dropdown-divider"></div>
                <a class="dropdown-item" href="{% url 'auth:logout' %}">
                  <i class="mdi mdi-logout me-2 text-primary"></i> Chiqish </a>
              </div>
            </li>
          </ul>
          <button class="navbar-toggler navbar-toggler-right d-lg-none align-self-center" type="button" data-toggle="offcanvas">
            <span class="mdi mdi-menu"></span>
          </button>
        </div>
      </nav>
      <!-- partial -->
      <div class="container-fluid page-body-wrapper">
        <!-- partial:partials/_sidebar.html -->
        <nav class="sidebar sidebar-offcanvas" id="sidebar">
          <ul class="nav">
            <li class="nav-item">
              <a class="nav-link" data-bs-toggle="collapse" href="#category" aria-expanded="false" aria-controls="category">
                <span class="menu-title">Kategoriya</span>
              </a>
              <div class="collapse" id="category">
                <ul class="nav flex-column sub-menu">
                  <li class="nav-item">
                    <a class="nav-link" href="{% url 'dashboard:category_create' %}">Yaratish</a>
                  </li>
                  <li class="nav-item">
                    <a class="nav-link" href="{% url 'dashboard:category_list' %}">Ro'yxat</a>
                  </li>
                </ul>
              </div>
            </li>
            <li class="nav-item">
              <a class="nav-link" data-bs-toggle="collapse" href="#icons" aria-expanded="false" aria-controls="icons">
                <span class="menu-title">Mahsulot</span>
              </a>
              <div class="collapse" id="icons">
                <ul class="nav flex-column sub-menu">
                  <li class="nav-item">
                    <a class="nav-link" href="{% url 'dashboard:product_create' %}">Yaratish</a>
                  </li>
                  <li class="nav-item">
                    <a class="nav-link" href="{% url 'dashboard:product_list' %}">Ro'yxat</a>
                  </li>
                </ul>
              </div>
            </li>
            <li class="nav-item">
              <a class="nav-link" data-bs-toggle="collapse" href="#forms" aria-expanded="false" aria-controls="forms">
                <span class="menu-title">Kirim</span>
              </a>
              <div class="collapse" id="forms">
                <ul class="nav flex-column sub-menu">
                  <li class="nav-item">
                    <a class="nav-link" href="{% url 'dashboard:enter_create' %}">Yaratish</a>
                  </li>
                  <li class="nav-item">
                    <a class="nav-link" href="{% url 'dashboard:enter_list' %}">Ro'yxat</a>
                  </li>
                </ul>
              </div>
            </li>
            <li class="nav-item">
              <a class="nav-link" data-bs-toggle="collapse" href="#charts" aria-expanded="false" aria-controls="charts">
                <span class="menu-title">Chiqim</span>
              </a>
              <div class="collapse" id="charts">
                <ul class="nav flex-column sub-menu">
                  <li class="nav-item">
                    <a class="nav-link" href="{% url 'dashboard:out_create' %}">Yaratish</a>
                  </li>
                  <li class="nav-item">
                    <a class="nav-link" href="{% url 'dashboard:out_list' %}">Ro'yxat</a>
                  </li>
                </ul>
              </div>
            </li>
            <li class="nav-item">
              <a class="nav-link" data-bs-toggle="collapse" href="#tables" aria-expanded="false" aria-controls="tables">
                <span class="menu-title">Buyurtma</span>
              </a>
              <div class="collapse" id="tables">
                <ul class="nav flex-column sub-menu">
                  <li class="nav-item">
                    <a class="nav-link" href="{% url 'dashboard:order_create' %}">Yaratish</a>
                  </li>
                  <li class="nav-item">
                    <a class="nav-link" href="{% url 'dashboard:order_list' %}">Ro'yxat</a>
                  </li>
                </ul>
              </div>
            </li>
            <li class="nav-item">
              <a class="nav-link" data-bs-toggle="collapse" href="#something" aria-expanded="false" aria-controls="something">
                <span class="menu-title">Buyurtma Mahsulot</span>
              </a>
              <div class="collapse" id="something">
                <ul class="nav flex-column sub-menu">
                  <li class="nav-item">
                    <a class="nav-link" href="{% url 'dashboard:order_product_create' %}">Yaratish</a>
                  </li>
                  <li class="nav-item">
                    <a class="nav-link" href="{% url 'dashboard:order_product_list' %}">Ro'yxat</a>
                  </li>
                </ul>
              </div>
            </li>
          </ul>
        </nav>
        <!-- partial -->
        
        {% block content %}
  
        {% endblock content %}

        <!-- main-panel ends -->
      </div>
      <!-- page-body-wrapper ends -->
    </div>
    <!-- container-scroller -->
    <!-- plugins:js -->
    <script src="{% static 'vendors/js/vendor.bundle.base.js' %}"></script>
    <!-- endinject -->
    <!-- Plugin js for this page -->
    <script src="{% static 'vendors/chart.js/chart.umd.js' %}"></script>
    <script src="{% static 'vendors/bootstrap-datepicker/bootstrap-datepicker.min.js' %}"></script>
    <!-- End plugin js for this page -->
    <!-- inject:js -->
    <script src="{% static 'js/off-canvas.js' %}"></script>
    <script src="{% static 'js/misc.js' %}"></script>
    <script src="{% static 'js/settings.js' %}"></script>
    <script src="{% static 'js/todolist.js' %}"></script>
    <script src="{% static 'js/jquery.cookie.js' %}"></script>
    <!-- endinject -->
    <!-- Custom js for this page -->
    <script src="{% static 'js/dashboard.js' %}"></script>
    <!-- End custom js for this page -->
  </body>
</html>

templates/dashboard/index.html
{% extends 'dashboard/base.html' %}
{% load static %}
{% block content %}
<div class="main-panel">
    <div class="content-wrapper">
      <div class="page-header">
        <h3 class="page-title">
          <span class="page-title-icon bg-gradient-primary text-white me-2">
            <i class="mdi mdi-home"></i>
          </span> Dashboard
        </h3>
        <nav aria-label="breadcrumb">
            <form method="get">
          <ul class="breadcrumb">
            <li class="breadcrumb-item active" aria-current="page">
                <select name="product_code" class="form-control">
                    <option value="0">Barchasi</option>
                    {% for product in queryset %}
                    <option value="{{product.code}}" {% if product.code == product_code %} selected {% endif %}>{{product}}</option>
                    {% endfor %}
                </select>
            </li>
            <li class="breadcrumb-item active" aria-current="page">
                <button class=" btn btn-success " type="submit">Filterlash</button>
            </li>
          </ul>
        </form>
        </nav>
      </div>
      <div class="row">
        <div class="col-md-4 stretch-card grid-margin">
          <div class="card bg-gradient-danger card-img-holder text-white">
            <div class="card-body">
              <img src="{% static 'images/dashboard/circle.svg' %}" class="card-img-absolute" alt="circle-image" />
              <h4 class="font-weight-normal mb-3"> Barcha ahsulotlar soni<i class="mdi mdi-chart-line mdi-24px float-end"></i>
              </h4>
              <h2 class="mb-5">{{product_count}}</h2>
            </div>
          </div>
        </div>
        <div class="col-md-4 stretch-card grid-margin">
          <div class="card bg-gradient-info card-img-holder text-white">
            <div class="card-body">
              <img src="{% static 'images/dashboard/circle.svg' %}" class="card-img-absolute" alt="circle-image" />
              <h4 class="font-weight-normal mb-3"> Kirimlar umumiy qiymati <i class="mdi mdi-bookmark-outline mdi-24px float-end"></i>
              </h4>
              <h2 class="mb-5">{{total_enter}}</h2>
            </div>
          </div>
        </div>
        <div class="col-md-4 stretch-card grid-margin">
          <div class="card bg-gradient-success card-img-holder text-white">
            <div class="card-body">
              <img src="{% static 'images/dashboard/circle.svg' %}" class="card-img-absolute" alt="circle-image" />
              <h4 class="font-weight-normal mb-3"> Chiqimlar umumiy qiymati<i class="mdi mdi-diamond mdi-24px float-end"></i>
              </h4>
              <h2 class="mb-5">{{total_out}}</h2>
            </div>
          </div>
        </div>
      </div>
      <div class="row">
        <div class="col-12 grid-margin">
          <div class="card">
            <div class="card-body">
              <h4 class="card-title">Recent Tickets</h4>
              <div class="table-responsive">
                <table class="table">
                  <thead>
                    <tr>
                      <th> Product </th>
                      <th> Miqdori </th>
                      <th> Sanasi </th>
                    </tr>
                  </thead>
                  <tbody>
                    {% for p in all %}
                      <tr>
                        <td>{{p.product}}</td>
                        <td>{{p.quantity}}</td>
                        <td>{{p.date}}</td>
                        </tr>
                    {% endfor %}
                  </tbody>
                </table>
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>
    <!-- content-wrapper ends -->
  </div>
{% endblock content %}